In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Paso 1: Crear un conjunto de datos de ejemplo
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Paso 2: Crear el escalador
scaler = StandardScaler()

# Paso 3: Ajustar el escalador a los datos
scaler.fit(X)

# Paso 4: Transformar los datos
X_scaled = scaler.transform(X)

print("Datos originales:")
print(X)
print("Datos escalados:")
print(X_scaled)


Datos originales:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Datos escalados:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [1]:
for i in range(1, 10):
    print(i)

1
2
3
4
5
6
7
8
9
